jobs:
  Job1:
    name: Job 1
    steps: []
  Job2:
    name: Job 2
dependencies:
  - Project1_SubProject1_Build2:
      reuse: none
      enforce-revisions-synchronisation: true
      on-failed-dependency: run-add-problem
      on-incomplete-dependency: mark-as-failed-to-start
