version: 1
dependencies:
  - Chubatova20261tenant1_Build
jobs:
  Job3:
    name: Job 3
    runs-on:
      self-hosted:
        - requirement: not-equals
          name: RQ_1
          parameter: teamcity.agent.jbHosted
          value: 'true'
        - cpu: 2
        - requirement: not-contains
          name: RQ_3
          parameter: teamcity.agent.name
          value: kuku
  Job2:
    name: Job 2
    runs-on:
      self-hosted:
        - requirement: not-equals
          name: RQ_1
          parameter: teamcity.agent.jbHosted
          value: 'true'
        - requirement: not-equals
          name: RQ_2
          parameter: teamcity.agent.jbHosted
          value: 'true'
  Job1:
    name: Job 1
    steps:
      - script-content: echo a
        use:
          custom:
            script: true
        id: RUNNER_1
        type: script
      - type: script
        script-content: echo b
    runs-on:
      self-hosted:
        - requirement: not-equals
          name: RQ_1
          parameter: teamcity.agent.jbHosted
          value: 'true'
        - requirement: not-equals
          name: RQ_2
          parameter: teamcity.agent.jbHosted
          value: 'true'
