package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.*
import jetbrains.buildServer.configs.kotlin.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the buildType with id = 'Build2'
accordingly, and delete the patch script.
*/
changeBuildType(RelativeId("Build2")) {
    outputParams {
        remove {
            param("tpl1", "%tpl1%")
        }
    }
}
