package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.*
import jetbrains.buildServer.configs.kotlin.BuildType
import jetbrains.buildServer.configs.kotlin.buildFeatures.approval
import jetbrains.buildServer.configs.kotlin.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, create a buildType with id = 'Build2'
in the root project, and delete the patch script.
*/
create(DslContext.projectId, BuildType({
    id("Build2")
    name = "build2"

    params {
        param("a", "ax")
    }

    vcs {
        root(DslContext.settingsRoot)
        root(RelativeId("A"))
        root(RelativeId("HttpsGithubComChubatovaTigerManytags"))
    }

    features {
        approval {
            approvalRules = "user:user1"
            timeout = 1
            manualRunsApproved = false
        }
    }
}))

