package patches.projects

import jetbrains.buildServer.configs.kotlin.*
import jetbrains.buildServer.configs.kotlin.Project
import jetbrains.buildServer.configs.kotlin.projectFeatures.AwsConnection
import jetbrains.buildServer.configs.kotlin.projectFeatures.S3Storage
import jetbrains.buildServer.configs.kotlin.projectFeatures.activeStorage
import jetbrains.buildServer.configs.kotlin.projectFeatures.awsConnection
import jetbrains.buildServer.configs.kotlin.projectFeatures.s3Storage
import jetbrains.buildServer.configs.kotlin.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the root project
accordingly, and delete the patch script.
*/
changeProject(DslContext.projectId) {
    features {
        val feature1 = find<AwsConnection> {
            awsConnection {
                id = "AmazonWebServicesAws"
                name = "Amazon Web Services (AWS)"
                regionName = "eu-west-1"
                credentialsType = static {
                    accessKeyId = "AKIA5JH2VERVDN3XW5GF"
                    secretAccessKey = "credentialsJSON:61577a37-2621-4f7a-b757-893b9dab7a6b"
                    stsEndpoint = "https://sts.eu-west-1.amazonaws.com"
                }
                allowInSubProjects = true
                allowInBuilds = true
            }
        }
        feature1.apply {
        }
        val feature2 = find<S3Storage> {
            s3Storage {
                id = "PROJECT_EXT_5"
                storageName = "nm"
                bucketName = "chubatovatransferacceleration"
                bucketPrefix = "prefprefchubatova1109"
                forceVirtualHostAddressing = true
                awsEnvironment = default {
                    awsRegionName = "eu-central-1"
                }
                connectionId = "AmazonWebServicesAws"
            }
        }
        feature2.apply {
        }
        remove {
            activeStorage {
                id = "PROJECT_EXT_6"
                activeStorageID = "PROJECT_EXT_5"
            }
        }
        add {
            activeStorage {
                id = "PROJECT_EXT_2"
                activeStorageID = "DefaultStorage"
            }
        }
        add {
            s3Storage {
                id = "PROJECT_EXT_3"
                storageName = "bla"
                bucketName = "chubatovawest1"
                bucketPrefix = "west"
                forceVirtualHostAddressing = true
                awsEnvironment = default {
                    awsRegionName = "eu-west-1"
                }
                connectionId = "AmazonWebServicesAws"
            }
        }
    }
}
