package patches.projects

import jetbrains.buildServer.configs.kotlin.*
import jetbrains.buildServer.configs.kotlin.Project
import jetbrains.buildServer.configs.kotlin.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, create a project with id = 'Proj8_Subp'
in the project with id = 'Proj8', and delete the patch script.
*/
create(RelativeId("Proj8"), Project({
    id("Proj8_Subp")
    name = "subp"
}))

