package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.*
import jetbrains.buildServer.configs.kotlin.BuildType
import jetbrains.buildServer.configs.kotlin.buildSteps.script
import jetbrains.buildServer.configs.kotlin.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, create a buildType with id = 'Hi'
in the root project, and delete the patch script.
*/
create(DslContext.projectId, BuildType({
    id("Hi")
    name = "hi"

    steps {
        script {
            id = "simpleRunner"
            scriptContent = """
                echo a
                echo '##teamcity[buildDetachedFromAgent]'
            """.trimIndent()
        }
        script {
            id = "simpleRunner_1"
            scriptContent = "sleep 20"
        }
    }
}))

