package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.*
import jetbrains.buildServer.configs.kotlin.buildFeatures.approval
import jetbrains.buildServer.configs.kotlin.buildSteps.Qodana
import jetbrains.buildServer.configs.kotlin.buildSteps.ScriptBuildStep
import jetbrains.buildServer.configs.kotlin.buildSteps.qodana
import jetbrains.buildServer.configs.kotlin.buildSteps.script
import jetbrains.buildServer.configs.kotlin.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the buildType with id = 'Build'
accordingly, and delete the patch script.
*/
changeBuildType(RelativeId("Build")) {
    expectSteps {
        script {
            id = "simpleRunner"
            scriptContent = "echo https://chubatova20261tenant1.dev.sandbox.teamcity.aws.intellij.net"
        }
    }
    steps {
        update<ScriptBuildStep>(0) {
            enabled = false
            clearConditions()
            scriptContent = "sleep 100"
            param("teamcity.kubernetes.executor.pull.policy", "")
        }
        insert(1) {
            qodana {
                id = "Qodana"
                enabled = false
                linter = jvm {
                    version = Qodana.JVMVersion.LATEST
                }
                inspectionProfile = default()
            }
        }
    }

    features {
        add {
            approval {
                approvalRules = "user:8ecfea6a-f953-49b9-b753-3797a71b2f3f_b6a3a8e4-a253-4859-b991-550530b48ba7"
            }
        }
    }
}
