package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.*
import jetbrains.buildServer.configs.kotlin.buildSteps.Qodana
import jetbrains.buildServer.configs.kotlin.buildSteps.ScriptBuildStep
import jetbrains.buildServer.configs.kotlin.buildSteps.qodana
import jetbrains.buildServer.configs.kotlin.buildSteps.script
import jetbrains.buildServer.configs.kotlin.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the buildType with id = 'Build'
accordingly, and delete the patch script.
*/
changeBuildType(RelativeId("Build")) {
    expectSteps {
        script {
            id = "simpleRunner"
            scriptContent = "echo https://chubatova20261tenant1.dev.sandbox.teamcity.aws.intellij.net"
        }
    }
    steps {
        update<ScriptBuildStep>(0) {
            clearConditions()
            scriptContent = "sleep 100"
            param("teamcity.kubernetes.executor.pull.policy", "")
        }
        insert(1) {
            qodana {
                id = "Qodana"
                linter = jvm {
                    version = Qodana.JVMVersion.LATEST
                }
                inspectionProfile = default()
            }
        }
    }
}
